home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

import_export/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('import_export/', views.BrandListView.as_view(), name='brands'),
]

sgtrade/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from news.views import NewsView
from quote.views import index

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('products.urls')),
    path('products/', include('products.urls')),
    path('', include('personal_account.urls')),
    path('news/', NewsView.as_view(), name='news'),
    path('quote/', index, name="index"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

import_export/models.py
from django.db import models


class Brand(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField('Изображение', upload_to='brands_img')

    def __str__(self):
        return f'{self.title},{self.image}'

import_export/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Brand


class BrandListView(ListView):
    model = Brand
    template_name = 'import_export/brands.html'

import_export/templates/import_export/brands.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="hero container d-flex" style="position: relative;">
        <img class="w-100 h-auto opacity-25" src="{% static 'img/truck.png' %}" alt="">

        <h1 class="text-light" style="position: absolute;top: 30%;left: 10%;width:375px;">
            Import/Export
        </h1>
        <div style="position: absolute;top: 45%;left: 10%;height: 4px;width: 100px;background-color: #04C1C1;"></div>
        <div class="text-light" style="position: absolute;top: 50%;left: 10%;width:375px;">
            At our company, we are dedicated to providing customers with a unique value proposition: well-known and
            reputable products at prices lower than those offered by manufacturers or their representatives. Our primary
            service revolves around the sale of established brands within the FMCG category.
        </div>
    </section>




    <section class="block-3  h-100 container d-flex align-items-center justify-content-center text-left">

        <div class="col-12 col-md-8 col-lg-5 ps-0 ps-md-2 ps-lg-4">
            <h2 class="text-light">Brands we Work with</h2>
            <div class="text-light">We offer a wide range of popular products, including</div>
            <div class="row">
                {% for brand in brand_list %}
                    <div class="col-2">
                        <img class="w-100" src="{{ brand.image.url }}" alt="">

                    </div>
                {% endfor %}
            </div>
        </div>

    </section>


{% endblock content %}